# Parameters for maskAL
# python maskAL.py --config maskAL.yaml
# explanation can be found here: https://git.wur.nl/blok012/maskAL

# folders
weightsroot: "./weights"
resultsroot: "./results"
dataroot: "./datasets/experiment/random"
initial_train_dir: "./datasets"
traindir: "./datasets/train"
valdir: "./datasets/val"
testdir: "./datasets/test03"

# data options
use_initial_train_dir: False
duplicate_initial_model_and_data: True
initial_train_file: "./results/experiment/uncertainty/trainfiles_iteration000.txt"

# network parameters
network_config: COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml
pretrained_weights: "./weights/experiment/uncertainty/best_model_000.pth"

# training-parameters
cuda_visible_devices: '1'
classes: ['healthy', 'damaged', 'matured', 'cateye', 'headrot']
transfer_learning_on_previous_models: True
learning_rate: 0.005
warmup_iterations: 500
train_iterations_base: 2500
train_iterations_step_size: 2500
step_image_number: 500
step_ratios: [0.5, 0.8]
eval_period: 500
checkpoint_period: -1
weight_decay: 0.0001
learning_policy: 'steps_with_decay'
gamma: 0.1
train_batch_size: 1
num_workers: 2

# train-sampler
train_sampler: "RepeatFactorTrainingSampler"
minority_classes: ['damaged', 'matured', 'cateye', 'headrot']
repeat_factor_smallest_class: 1.5

# evaluation-parameters
confidence_threshold: 0.5
nms_threshold: 0.01

# active-learning sampling
experiment_name: 'experiment'
strategy: 'random'
mode: 'mean'
initial_datasize: 100
pool_size: 200
equal_pool_size: True
loops: 5
dropout_probability: 0.25
mcd_iterations: 20
iou_thres: 0.5
auto_annotate: False
export_format: labelme
supervisely_meta_json: "./datasets/meta.json"
